environment:
  matrix:
    - TOXENV: py27
    - TOXENV: py35
    - TOXENV: py36
    - TOXENV: py37

install:
  - py -m pip install -U pip
  - py -m pip install --user tox tox-appveyor
  - py bin/downloads.py

build: off

test_script:
  - py -m tox
