language:
  python

python:
  - 3.5
  - 3.6
  - 3.7-dev

addons:
  apt:
    packages:
      - clang

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install -U pipenv
  - pipenv --version
  - pipenv install --dev
  - pipenv run python bin/downloads.py

script:
  - pipenv run python ./runtest.py -e -a
