language:
  python

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7-dev

env:
  - LOCAL_CXXTEST=true
  - LOCAL_CXXTEST=false

addons:
  apt:
    packages:
      - cxxtest

install:
  - pip install -U pip
  - pip --version
  - pip install tox-travis
  - python bin/downloads.py scons-test
  - if $LOCAL_CXXTEST; then python bin/downloads.py cxxtest; fi

script:
  - tox
